import type { ClientDossier } from "./clientTypes";

/**
 * Static mock dossiers — one per client used in the campaign mock.
 * Some fields are intentionally left empty to exercise the honest "N/D" state.
 */
export const CLIENT_DOSSIERS: ClientDossier[] = [
  {
    client: "Aurora Cosméticos",
    fields: {
      instagram: "https://instagram.com/auroracosmeticos",
      site: "https://auroracosmeticos.com.br",
      gmb: "https://maps.google.com/?cid=aurora",
      endereco: "Rua das Acácias, 210 — Pinheiros, São Paulo/SP",
      drive: "https://drive.google.com/drive/folders/aurora",
      nome: "Aurora Cosméticos",
      tagline: "Beleza que nasce da natureza",
      proposito:
        "Democratizar o acesso a cosméticos naturais de alta performance,\ncom fórmulas veganas e embalagens recicláveis.",
      valores: "Transparência\nSustentabilidade\nCiência aplicada",
      personalidade: "Acolhedora, informativa e otimista.",
      tomVoz: "Próximo e educativo. Evita jargão técnico sem explicação.",
      mensagensChave:
        "1. Fórmula 100% vegana testada dermatologicamente.\n2. Resultado visível em 14 dias.\n3. Embalagem retornável.",
      evitar: "Promessas milagrosas, comparações diretas com concorrentes.",
      publicoAlvo: "Mulheres 25–45, classes A/B, interessadas em skincare limpo.",
      personas: "Marina, 32, publicitária, compra por indicação e reviews.",
      concorrentes: "Simple Organic, Sallve, Océane",
      diferenciais: "Linha refil, laudo dermatológico público, frete verde.",
      responsavel: "Camila Duarte",
      email: "camila@auroracosmeticos.com.br",
      telefone: "+55 11 98123-4455",
      financeiro: "Financeiro Aurora — pagamentos@auroracosmeticos.com.br",
      produtos: "Skincare (limpeza, hidratação, proteção) e linha capilar.",
      ticket: "R$ 189,00",
      funil: "Awareness (vídeo) → Remarketing catálogo → Cupom primeira compra.",
      objecoes: "Preço acima da média; dúvida sobre eficácia de cosmético natural.",
      gatilhos: "Prova social, antes/depois, frete grátis acima de R$ 199.",
      logos: "https://drive.google.com/drive/folders/aurora-logos",
      fotos: "https://drive.google.com/drive/folders/aurora-fotos",
      paleta: "#F2E3D5 areia\n#2F4F3E verde profundo\n#C9743B terracota",
      tipografia: "Canela (títulos) + Inter (texto)",
      manualMarca: "https://drive.google.com/file/d/aurora-manual",
      metaPrincipal: "Escalar faturamento de mídia paga em 40% até dezembro.",
      kpis: "ROAS ≥ 4,0 · CPA ≤ R$ 55 · Receita incremental",
      orcamento: "R$ 60.000/mês",
    },
  },
  {
    client: "Helix Fitness",
    fields: {
      instagram: "https://instagram.com/helixfitness",
      site: "https://helixfitness.com.br",
      endereco: "Av. Beira-Mar, 1200 — Boa Viagem, Recife/PE",
      whatsappGrupo: "https://chat.whatsapp.com/helix-midia",
      nome: "Helix Fitness",
      tagline: "Evolua em espiral",
      proposito: "Tornar o treino de força acessível para iniciantes adultos.",
      personalidade: "Direta, energética e sem julgamento.",
      tomVoz: "Motivacional, frases curtas, segunda pessoa.",
      mensagensChave: "Primeiro mês sem taxa de matrícula.\nAvaliação física inclusa.",
      evitar: "Estética corporal como única motivação.",
      publicoAlvo: "Adultos 24–45 na zona sul do Recife.",
      concorrentes: "Smart Fit, Bluefit, academias de bairro",
      diferenciais: "Professores por aluno 1:8, app de acompanhamento.",
      responsavel: "Rodrigo Sena",
      email: "rodrigo@helixfitness.com.br",
      telefone: "+55 81 99604-1188",
      produtos: "Planos mensal, trimestral e anual; personal trainer.",
      ticket: "R$ 129,90/mês",
      funil: "Lead form → Contato em 5 min → Aula experimental → Matrícula.",
      objecoes: "Fidelidade contratual, distância da unidade.",
      gatilhos: "Aula experimental gratuita, urgência de lote promocional.",
      logos: "https://drive.google.com/drive/folders/helix-logos",
      paleta: "#0F1D2B azul noite\n#39E27D verde neon",
      tipografia: "Archivo Expanded",
      metaPrincipal: "500 matrículas novas por trimestre.",
      kpis: "CPL ≤ R$ 18 · Taxa de comparecimento ≥ 55%",
      prazo: "Q4/2026",
    },
  },
  {
    client: "Nimbus SaaS",
    fields: {
      site: "https://nimbus.cloud",
      instagram: "https://instagram.com/nimbussaas",
      drive: "https://drive.google.com/drive/folders/nimbus",
      nome: "Nimbus SaaS",
      tagline: "Operações previsíveis, sem planilha",
      proposito: "Dar a times de operações visibilidade em tempo real.",
      valores: "Clareza\nAutonomia do cliente\nSegurança por padrão",
      personalidade: "Analítica, sóbria, confiante.",
      tomVoz: "Técnico e objetivo, orientado a dados.",
      mensagensChave: "Implementação em 7 dias.\nIntegra com ERP legado.",
      evitar: "Superlativos vazios e comparativos agressivos.",
      publicoAlvo: "Gestores de operações em empresas de 50–500 funcionários.",
      personas: "Paulo, 41, COO; avalia ROI e risco de migração.",
      concorrentes: "Pipefy, Monday, planilhas internas",
      diferenciais: "Onboarding assistido e SLA de suporte em 2h.",
      responsavel: "Letícia Amorim",
      email: "leticia@nimbus.cloud",
      produtos: "Plano Core, Plano Scale, módulo de BI.",
      ticket: "R$ 2.400 MRR",
      funil: "Conteúdo → Demo agendada → Trial 14 dias → Contrato anual.",
      objecoes: "Migração de dados, custo por assento.",
      gatilhos: "Estudo de caso do mesmo setor, trial sem cartão.",
      documentos: "https://drive.google.com/drive/folders/nimbus-legal",
      paleta: "#101418 grafite\n#4C8DFF azul produto\n#F5F7FA claro",
      tipografia: "IBM Plex Sans",
      metaPrincipal: "Dobrar o MRR proveniente de mídia paga em 12 meses.",
      kpis: "CAC ≤ R$ 3.500 · Demos qualificadas/mês ≥ 60",
      prazo: "Jun/2027",
      orcamento: "R$ 45.000/mês",
    },
  },
  {
    client: "Verdant Foods",
    fields: {
      instagram: "https://instagram.com/verdantfoods",
      site: "https://verdantfoods.com.br",
      gmb: "https://maps.google.com/?cid=verdant",
      endereco: "Rod. Anhanguera, km 88 — Campinas/SP",
      nome: "Verdant Foods",
      tagline: "Comida de verdade, direto do campo",
      proposito: "Encurtar a distância entre produtor e mesa.",
      valores: "Origem rastreável\nDesperdício zero",
      personalidade: "Rústica, honesta, calorosa.",
      tomVoz: "Coloquial e afetivo, com referências ao campo.",
      mensagensChave: "Entrega semanal de orgânicos certificados.",
      publicoAlvo: "Famílias urbanas 30–55 preocupadas com alimentação.",
      concorrentes: "Fazenda da Toca, mercados locais, feiras",
      diferenciais: "Assinatura flexível e produtor identificado na etiqueta.",
      responsavel: "João Bertoldi",
      email: "joao@verdantfoods.com.br",
      telefone: "+55 19 99777-2020",
      operacional: "Central de logística — logistica@verdantfoods.com.br",
      produtos: "Cestas de assinatura, avulsos, kits sazonais.",
      ticket: "R$ 219,00",
      objecoes: "Preço vs. supermercado, receio de produto perecível.",
      gatilhos: "Primeira cesta com desconto, garantia de frescor.",
      fotos: "https://drive.google.com/drive/folders/verdant-fotos",
      paleta: "#22331F verde folha\n#E8DFC8 palha",
      grafismos: "Textura de papel kraft e ilustrações botânicas.",
      metaPrincipal: "Chegar a 3.000 assinaturas ativas.",
      kpis: "CPA ≤ R$ 70 · Churn mensal ≤ 6%",
    },
  },
  {
    client: "Orbit Travel",
    fields: {
      instagram: "https://instagram.com/orbittravel",
      site: "https://orbittravel.com.br",
      whatsappGrupo: "https://chat.whatsapp.com/orbit-midia",
      drive: "https://drive.google.com/drive/folders/orbit",
      nome: "Orbit Travel",
      tagline: "Roteiros que giram em torno de você",
      proposito: "Planejar viagens sob medida sem burocracia.",
      personalidade: "Aspiracional, organizada, cosmopolita.",
      tomVoz: "Inspirador com informação prática (preço, prazo, roteiro).",
      mensagensChave: "Parcelamento em 12x.\nConsultor dedicado por viagem.",
      evitar: "Imagens genéricas de banco de imagens.",
      publicoAlvo: "Casais 28–50 e famílias planejando viagens internacionais.",
      personas: "Bruna, 36, planeja com 6 meses de antecedência.",
      concorrentes: "CVC, Decolar, agências boutique",
      diferenciais: "Roteiro personalizado e suporte em viagem 24h.",
      responsavel: "Tatiana Rocha",
      email: "tatiana@orbittravel.com.br",
      telefone: "+55 21 98800-3311",
      produtos: "Pacotes personalizados, cruzeiros, seguro viagem.",
      ticket: "R$ 8.400",
      funil: "Anúncio de destino → WhatsApp → Cotação → Fechamento.",
      objecoes: "Confiança na agência, câmbio, cancelamento.",
      logos: "https://drive.google.com/drive/folders/orbit-logos",
      videos: "https://drive.google.com/drive/folders/orbit-videos",
      paleta: "#12224A azul profundo\n#F2B441 âmbar",
      tipografia: "Playfair Display + Inter",
      metaPrincipal: "Aumentar receita de alta temporada em 35%.",
      kpis: "ROAS ≥ 6,0 · Custo por cotação ≤ R$ 90",
      prazo: "Dez/2026",
      orcamento: "R$ 38.000/mês",
    },
  },
  {
    client: "Forge Tools",
    fields: {
      site: "https://forgetools.com.br",
      gmb: "https://maps.google.com/?cid=forge",
      endereco: "Distrito Industrial, Galpão 14 — Joinville/SC",
      nome: "Forge Tools",
      tagline: "Feito para durar turno após turno",
      proposito: "Equipar profissionais com ferramentas de nível industrial.",
      valores: "Durabilidade\nAssistência técnica própria",
      personalidade: "Robusta, técnica, sem floreio.",
      tomVoz: "Objetivo, focado em especificação e garantia.",
      mensagensChave: "3 anos de garantia.\nPeças de reposição sempre disponíveis.",
      publicoAlvo: "Profissionais da construção civil e marcenaria.",
      concorrentes: "Bosch, Makita, importados genéricos",
      diferenciais: "Rede autorizada nacional e catálogo de peças aberto.",
      responsavel: "Marcos Iwata",
      email: "marcos@forgetools.com.br",
      telefone: "+55 47 99215-7788",
      financeiro: "financeiro@forgetools.com.br",
      produtos: "Furadeiras, serras, kits profissionais, acessórios.",
      ticket: "R$ 1.150",
      funil: "Pesquisa de marca/produto → PDP → Checkout ou revenda.",
      objecoes: "Preço vs. importado, prazo de assistência.",
      gatilhos: "Garantia estendida, comparativo técnico.",
      documentos: "https://drive.google.com/drive/folders/forge-legal",
      paleta: "#1A1A1A grafite\n#FF6A13 laranja sinal",
      metaPrincipal: "Reduzir CPA do e-commerce mantendo volume.",
      kpis: "CPA ≤ R$ 140 · ROAS ≥ 3,5",
    },
  },
];
